-- Referentie — reeds toegepast op Supabase (project xftnovnldcdfohqlqgor).
-- Alleen ter documentatie; niet nodig om opnieuw te draaien.

CREATE TABLE IF NOT EXISTS public.inkoop_leads (
  ad_id             text PRIMARY KEY,
  titel             text,
  beschrijving      text,
  prijs             int,
  plaats            text,
  land              text,
  verkoper_id       text,
  verkoper_naam     text,
  is_particulier    boolean DEFAULT true,
  url               text,
  foto_url          text,
  bron              text,
  advertentie_datum timestamptz,
  status            text DEFAULT 'nieuw',   -- nieuw | bekeken | genegeerd | naar_inkoop
  gevonden_op       timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inkoop_leads_status_idx   ON public.inkoop_leads (status);
CREATE INDEX IF NOT EXISTS inkoop_leads_gevonden_idx ON public.inkoop_leads (gevonden_op DESC);
-- Opruimen: de dagelijkse job verwijdert leads ouder dan het ingestelde aantal
-- dagen (instellingen.inkoop_bewaar_dagen, default 5; fallback env RADAR_BEWAAR_DAGEN)
-- op basis van gevonden_op; status 'naar_inkoop' blijft altijd staan.
-- De admin stelt dit aantal in op de Instellingen-pagina:
--   ALTER TABLE public.instellingen
--     ADD COLUMN IF NOT EXISTS inkoop_bewaar_dagen int NOT NULL DEFAULT 5;

ALTER TABLE public.inkoop_leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY inkoop_leads_admin ON public.inkoop_leads
  FOR ALL USING (is_admin()) WITH CHECK (is_admin());

CREATE TABLE IF NOT EXISTS public.inkoop_radar_status (
  id           int PRIMARY KEY DEFAULT 1,
  laatste_run  timestamptz,
  http_ok      boolean,
  gevonden     int,
  gemapt       int,
  nieuw        int,
  waarschuwing text,
  CONSTRAINT inkoop_radar_status_single_row CHECK (id = 1)
);
INSERT INTO public.inkoop_radar_status (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.inkoop_radar_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY inkoop_radar_status_admin ON public.inkoop_radar_status
  FOR ALL USING (is_admin()) WITH CHECK (is_admin());

-- Handmatig beheerde lijst met populaire motormodellen (bron: motoroccasion.nl
-- "Meest getoond in deze maand"). De admin vult deze zelf, onbeperkt aantal.
-- Leads waarvan titel/beschrijving een term bevat, komen in de inkoop-tab
-- bovenaan met een 🔥-badge; er is ook een knop die alléén populaire toont.
CREATE TABLE IF NOT EXISTS public.inkoop_populair (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term        text NOT NULL,
  rang        int  NOT NULL DEFAULT 0,   -- lager = hoger in de lijst
  aangemaakt  timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inkoop_populair_rang_idx ON public.inkoop_populair (rang);

ALTER TABLE public.inkoop_populair ENABLE ROW LEVEL SECURITY;
CREATE POLICY inkoop_populair_admin ON public.inkoop_populair
  FOR ALL USING (is_admin()) WITH CHECK (is_admin());
